### ISSUE TITLE
Simbert参数问题

### ISSUE THREAD

**Issue by yc1999** [425776024/nlpcda#12]
https://github.com/425776024/nlpcda/blob/254ed886746d25812571ebe2616379254ffad104/nlpcda/tools/Simbert.py#L16-L17

请问上面代码中的`config[’device‘]`参数有什么用吗？代码中好像没有体现出其作用，请多指教。

**Comment by 425776024** [comment]
> https://github.com/425776024/nlpcda/blob/254ed886746d25812571ebe2616379254ffad104/nlpcda/tools/Simbert.py#L16-L17
> 
> 请问上面代码中的`config[’device‘]`参数有什么用吗？代码中好像没有体现出其作用，请多指教。

这个Simbert实现、解释的不是很好，推荐看看原作者的。

**Comment by 425776024** [comment]
> https://github.com/425776024/nlpcda/blob/254ed886746d25812571ebe2616379254ffad104/nlpcda/tools/Simbert.py#L16-L17
> 
> 请问上面代码中的`config[’device‘]`参数有什么用吗？代码中好像没有体现出其作用，请多指教。

**Comment by yc1999** [comment]
> > https://github.com/425776024/nlpcda/blob/254ed886746d25812571ebe2616379254ffad104/nlpcda/tools/Simbert.py#L16-L17
> > 
> > 请问上面代码中的`config[’device‘]`参数有什么用吗？代码中好像没有体现出其作用，请多指教。
> 
> 这个Simbert实现、解释的不是很好，推荐看看原作者的。一直想抽空优化这个，包括注释，比较忙就没时间弄了

好的。

**Comment by doosenn** [comment]
我使用的时候会错误，这个device怎么改呢？
python3.6/site-packages/nlpcda/tools/Simbert.py in __init__(self, config)
     15     def __init__(self, config: dict = {}):
     16         if config.get('device') is None:
---> 17             config['device'] = self._config['device']
     18         if config.get('max_len') is None:
     19             config['max_len'] = self._config['max_len']

KeyError: 'device'

**Comment by 425776024** [comment]
这个已经修复了
