### ISSUE TITLE
NER下的attribute问题

### ISSUE THREAD

**Issue by Don-ECNU** [425776024/nlpcda#3]
你好，谢谢你的开源项目！
我在使用你的NER增强模块的时候发现，跑你样例里的代码
`data_sentence_arrs, data_label_arrs = ner.augment(file_name='0.txt')`的时候会报错说
AttributeError: 'tuple' object has no attribute 'augment'
在敲上“Ner.”之后能蹦出来augment方法但把ner传入self也不行……
（python用的不太熟悉，大佬大概知道这个是什么问题么呜呜呜谢谢！）

**Comment by 425776024** [comment]
你好，能发我全部调用代码吗？NER这个

**Comment by 425776024** [comment]
> 你好，谢谢你的开源项目！
> 我在使用你的NER增强模块的时候发现，跑你样例里的代码
> `data_sentence_arrs, data_label_arrs = ner.augment(file_name='0.txt')`的时候会报错说
> AttributeError: 'tuple' object has no attribute 'augment'
> 在敲上“Ner.”之后能蹦出来augment方法但把ner传入self也不行……
> （python用的不太熟悉，大佬大概知道这个是什么问题么呜呜呜谢谢！）

知道问题了，ner定义的时候后面加了个’  ,  ‘ ，    我那个README样例里的代码加了个逗号，导致ner被定义成 元组 tuple了，你把后面的逗号去掉：这样

```python
ner = Ner(ner_dir_name='ner_data',
        ignore_tag_list=['O'],
        data_augument_tag_list=['P', 'LOC','ORG'],
        augument_size=3, seed=0)

```

**Comment by Don-ECNU** [comment]
Tks！
