### ISSUE TITLE
NER数据增强具体方式是什么呢？

### ISSUE THREAD

**Issue by drxmy** [425776024/nlpcda#5]
您好，可以大概说一下NER增强的方式吗？比如是随机删减还是别的什么方式？谢谢！

**Comment by 425776024** [comment]
> 您好，可以大概说一下NER增强的方式吗？比如是随机删减还是别的什么方式？谢谢！

对同类型的实体进行置换，对于数据集目录下所有实体抽取出来，相同实体的实体之间替换

**Comment by drxmy** [comment]
感谢回答！
