### ISSUE TITLE
第五种方式小bug修改

### ISSUE THREAD

**Issue by sudan1024** [425776024/nlpcda#7]
第五种方式 NER数据增强中，对两个连在一起的实体，**代码识别的时候会把两个实体识别成一个**。我在Ner的源码中第69行改了这行代码就可以解决这个问题：
`elif pre_tag == tp_tag and t_label[0]!='B': #上一标签 = 当前标签`

**Comment by 425776024** [comment]
> 第五种方式 NER数据增强中，对两个连在一起的实体，**代码识别的时候会把两个实体识别成一个**。我在Ner的源码中第69行改了这行代码就可以解决这个问题：
> `elif pre_tag == tp_tag and t_label[0]!='B': #上一标签 = 当前标签`

👍

**Comment by sudan1024** [comment]
你好大佬！ 我想请问一下你时候参考比赛用了哪些方式的数据增强呢 如果对于NER的BIO数据除了第五种还可以使用哪些比较好呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "425776024/nlpcda"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:01
收件人:&nbsp;"425776024/nlpcda"<nlpcda@noreply.github.com&gt;;
抄送:&nbsp;"刘树东"<1534691620@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [425776024/nlpcda] 第五种方式小bug修改 (#7)





  
第五种方式 NER数据增强中，对两个连在一起的实体，代码识别的时候会把两个实体识别成一个。我在Ner的源码中第69行改了这行代码就可以解决这个问题：
 elif pre_tag == tp_tag and t_label[0]!='B': #上一标签 = 当前标签
  
👍

**Comment by 425776024** [comment]
只用了需要词典的那几个。NER知道不多
